---
name: Go
on:
  push:
    branches:
      - main
  pull_request:
    types:
       - unlabeled # if GitHub Actions stuck, add and remove "no ci" label to force rebuild
       - opened
       - reopened
       - synchronize
  schedule:
    - cron: "12 2 * * *"

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOLANGCI_LINT_CACHE: /home/runner/go/cache/lint
  GOMODCACHE: /home/runner/go/mod
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'no ci')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show environment
        run: env

      - name: Setup Go
        uses: ./setup-go
        with:
          cache-key: test

      - name: Run tests
        run: go test -count=1 ./...

      - name: Check dirty
        run: |
          git status
          git diff --exit-code
