---
name: "Setup nushell"
description: "Setups nushell as /usr/local/bin/nu"

runs:
  using: "composite"
  steps:
    - name: Setup nushell
      run: ./setup-nushell.sh
      working-directory: ${{ github.action_path }}
      shell: bash
